### PR TITLE
Update default >= 0.3.0

### PR DESCRIPTION
**Pull request by cloudnautique**

### CODE REVIEW

**Comment by imikushin** [comment]
Doesn't seem to work for me:

```
==> rancher-01: Booting VM...
==> rancher-01: Waiting for machine to boot. This may take a few minutes...
    rancher-01: SSH address: 127.0.0.1:2222
    rancher-01: SSH username: rancher
    rancher-01: SSH auth method: private key
    rancher-01: Warning: Connection timeout. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
    rancher-01: Warning: Remote connection disconnect. Retrying...
```

**Comment by cloudnautique** [comment]
We switched to Ubuntu console by default. It copies it down on boot... Can you check with gui enabled?

**Comment by imikushin** [comment]
Hey, it turns you're right! I've just Ctrl+C'ed the `vagrant up` and went on. Now, when I've read your comment, I did `vagrant ssh` and it's working!

However, it's taking too long too boot. Is there a way to prepackage ubuntu-console image into the vagrant box maybe?

**Comment by deniseschannon** [comment]
Is there someway to fix the messages so that it says that it might take a bit to connect due to the downloading of the Ubuntu console? I agree that it's taking too long and looks as if there is some kind of error.

Or @imikushin has the idea of how to avoid it.

**Comment by cloudnautique** [comment]
Going to merge this... we have something in mind to make this better in one of the next rancheros releases.

**Comment by flecno** [comment]
Installing ubuntu-console on boot is really annoying. What's about prepackageing in rancheros or is there an option for installing by vagrant provisioning?

**Pull request merged**
